POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "black@black.com",
  "password": "pass"
}

###
POST http://localhost:8080/user/create
Content-Type: application/json
Authorization: Bearer:   eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9WSUVXIiwiQ0FOX0RFTEVURSIsIkNBTl9DUkVBVEUiXSwic3ViIjoiYmxhY2tAYmxhY2suY29tIiwiaWF0IjoxNzQwNzk1MTIwLCJleHAiOjE3NDk0MzUxMjB9.8v4ETdPfbqd12YC2y02QczRCeGtu6AiSfQYljEUJ4X4


{
  "firstName": "Pera",
  "lastName": "Peric",
  "email": "mejl2@gmail.com",
  "password": "sifrica",
  "permissions": [
    "CAN_VIW"
  ]
}

###
GET http://localhost:8080/dish
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9WSUVXIiwiQ0FOX0RFTEVURSIsIkNBTl9DUkVBVEUiXSwic3ViIjoiYmxhY2tAYmxhY2suY29tIiwiaWF0IjoxNzQwNzk1MTIwLCJleHAiOjE3NDk0MzUxMjB9.8v4ETdPfbqd12YC2y02QczRCeGtu6AiSfQYljEUJ4X4


###
DELETE http://localhost:8080/user/delete/1
Accept: application/json

###


GET http://localhost:8080/dish
Accept: application/json