GET http://localhost:8080/order
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9QTEFDRV9PUkRFUiIsIkNBTl9WSUVXIiwiQ0FOX0RFTEVURSIsIkNBTl9TRUFSQ0hfT1JERVIiLCJDQU5fQ1JFQVRFIl0sInN1YiI6ImRhcmxpbmdAY3B0LmNvbSIsImlhdCI6MTc0MDk1NTg0NywiZXhwIjoxNzQ5NTk1ODQ3fQ.8Qi4xQyMLQJbEITjoB-c2jGkIoQtNfiZ-LPqO-0etas

###
POST http://localhost:8080/dish/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9QTEFDRV9PUkRFUiIsIkNBTl9WSUVXIiwiQ0FOX1RSQUNLX09SREVSIiwiQ0FOX1NDSEVEVUxFX09SREVSIiwiQ0FOX0RFTEVURSIsIkNBTl9TRUFSQ0hfT1JERVIiLCJDQU5fQ0FOQ0VMX09SREVSIiwiQ0FOX0NSRUFURSJdLCJzdWIiOiJibGFja0BibGFjay5jb20iLCJpYXQiOjE3NDA5NTY4NDQsImV4cCI6MTc0OTU5Njg0NH0.T2Dv8hX7F_zgeu936wtwvMg0_c8LbupWCUCkC3yb66k

{
  "title": "meal2",
  "description": "desc3"
}

###
POST http://localhost:8080/order/place
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9QTEFDRV9PUkRFUiIsIkNBTl9WSUVXIiwiQ0FOX0RFTEVURSIsIkNBTl9TRUFSQ0hfT1JERVIiLCJDQU5fQ1JFQVRFIl0sInN1YiI6ImRhcmxpbmdAY3B0LmNvbSIsImlhdCI6MTc0MDk1NTg0NywiZXhwIjoxNzQ5NTk1ODQ3fQ.8Qi4xQyMLQJbEITjoB-c2jGkIoQtNfiZ-LPqO-0etas

{
  "dishes": ["Pigeon","meal2"]
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "black@black.com",
  "password": "pass"
}

###
POST http://localhost:8080/user/create
Content-Type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9QTEFDRV9PUkRFUiIsIkNBTl9WSUVXIiwiQ0FOX1RSQUNLX09SREVSIiwiQ0FOX1NDSEVEVUxFX09SREVSIiwiQ0FOX0RFTEVURSIsIkNBTl9TRUFSQ0hfT1JERVIiLCJDQU5fQ0FOQ0VMX09SREVSIiwiQ0FOX0NSRUFURSJdLCJzdWIiOiJibGFja0BibGFjay5jb20iLCJpYXQiOjE3NDA5NTY4NDQsImV4cCI6MTc0OTU5Njg0NH0.T2Dv8hX7F_zgeu936wtwvMg0_c8LbupWCUCkC3yb66k

{
  "firstName": "Pera",
  "lastName": "Peric",
  "email": "mejl2@gmail.com",
  "password": "sifrica",
  "permissions": [
    "CAN_VIW"
  ]
}

###
GET http://localhost:8080/dish
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJDQU5fRURJVCIsIkNBTl9QTEFDRV9PUkRFUiIsIkNBTl9WSUVXIiwiQ0FOX0RFTEVURSIsIkNBTl9TRUFSQ0hfT1JERVIiLCJDQU5fQ1JFQVRFIl0sInN1YiI6ImRhcmxpbmdAY3B0LmNvbSIsImlhdCI6MTc0MDk1NTg0NywiZXhwIjoxNzQ5NTk1ODQ3fQ.8Qi4xQyMLQJbEITjoB-c2jGkIoQtNfiZ-LPqO-0etas


###
DELETE http://localhost:8080/user/delete/1
Accept: application/json

###

